import 'dart:ui';

class AppColors {
  static const Color primary = Color(0xFF0D47A1);
  static const Color secondary = Color(0xFF1976D2);
  static const Color tertiary = Color(0xFF42A5F5);
  static const Color quaternary = Color(0xFFBBDEFB);
  static const Color quinary = Color(0xFFE3F2FD);
  static const Color senary = Color(0xFFE1F5FE);
  static const Color septenary = Color(0xFFB3E5FC);
  static const Color octonary = Color(0xFF81D4FA);
  static const Color nonary = Color(0xFF4FC3F7);
  static const Color denary = Color(0xFF29B6F6);
  static const Color white = Color(0xFFFFFFFF);
  static const Color black = Color(0xFF000000);
  static const Color grey = Color(0xFF9E9E9E);
  static const Color red = Color(0xFFD32F2F);
  static const Color green = Color(0xFF388E3C);
  static const Color yellow = Color(0xFFFBC02D);
  static const Color blue = Color(0xFF1976D2);
  static const Color orange = Color(0xFFFFA000);
  static const Color purple = Color(0xFF7B1FA2);
  static const Color brown = Color(0xFF5D4037);
  static const Color pink = Color(0xFFC2185B);
  static const Color teal = Color(0xFF00796B);
  static const Color cyan = Color(0xFF0097A7);
  static const Color lime = Color(0xFFAFB42B);
  static const Color amber = Color(0xFFFFC107);
  static const Color indigo = Color(0xFF303F9F);
  static const Color lightBlue = Color(0xFF03A9F4);
  static const Color lightGreen = Color(0xFF8BC34A);
  static const Color lightGrey = Color(0xFFE0E0E0);
  static const Color darkGrey = Color(0xFF616161);
  static const Color transparent = Color(0x00000000);
  static const Color transparentWhite = Color(0x80FFFFFF);
  static const Color transparentBlack = Color(0x80000000);
  static const Color transparentGrey = Color(0x809E9E9E);
  static const Color transparentRed = Color(0x80D32F2F);
  static const Color gradientpurplefirst = Color(0xFF7B1FA2);
  static const Color gradientpurplesecond = Color(0xFF7C4DFF);
}